Draft: Support for doctrine/migrations v3
laminas/laminas-diagnostics pull request #10
Opened 2020-09-26 12:27 UTC by cgrabenstein

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | maybe
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

I tried to tackle issue #7 and add support for `doctrine/migrations` v3. This PR introduces the `DependencyFactory` which is used to access the number of all migrations and the number of the executed ones. 

This change however is not compatible with v2, that's why I have marked it as a draft. I have no experience in how to support two different versions of a dependency and need some help here. 

If someone could show me a suitable way how to add support for v3 without breaking v2, I'll gladly update the code and finalize it by adding the required tests.

2020-09-28 16:16 UTC, weierophinney commented
I suggest bumping the minimum supported PHP version to at least 7.2 as part of this patch (if you look at the test matrix, 5.6 just fails entirely, and there's no reason to support unsupported PHP versions at this time).

One note - in the `--prefer-lowest` test jobs, we get a failure around the mock object passed to the DoctrineMigration constructor (see https://travis-ci.com/github/laminas/laminas-diagnostics/jobs/391297630#L2024); you may need to bump the minimum supported PHPUnit version to mitigate that.

2020-09-28 16:18 UTC, weierophinney commented
> One note - in the `--prefer-lowest` test jobs, we get a failure around the mock object passed to the DoctrineMigration constructor (see https://travis-ci.com/github/laminas/laminas-diagnostics/jobs/391297630#L2024); you may need to bump the minimum supported PHPUnit version to mitigate that.

And now I understand the request for help in your PR description, as this is due to the Doctrine Migrations version.

You have a couple of options.

One, remove the typehint, and check for one of the two types in the constructor, raising an exception for something that is neigher.

Two, introduce a different class for v3 of Doctrine Migrations, so users can switch between the versions based on what they have installed.

2020-09-28 19:47 UTC, cgrabenstein commented
Thanks for your input @weierophinney. Is there an option that you prefer? I'm good with both, although I slightly tend to option one, using one class, without the constructor typehint. It will avoid the confusion that will occur when having a `DoctrineMigration` and another `DoctrineMigrationV3` (?) class. 

I will update the draft accordingly. Let me know, should you prefer having two separate classes.

2020-09-28 20:26 UTC, weierophinney commented
As a maintainer, I tend to prefer stricter typing and less logical branching, but since this is an end-user facing class, and the original has no version in the name, I think option one will be less confusing for the user. Let's go with that!

2020-11-26 10:03 UTC, cgrabenstein commented
I finally had the time to finish the PR. Travis checks were not triggered, so I can't tell, if it works the way I implemented it. Help is appreciated.

2021-01-06 14:57 UTC, weierophinney commented
@cgrabenstein Please review the Travis build - there are a number of failing jobs, likely due to differences in which Doctrine Migrations version is being installed: https://travis-ci.com/github/laminas/laminas-diagnostics/builds/212201132

I'd suggest adding some code to the various test cases that are testing against specific migrations versions to skip if that version is not currently installed; as an example:

```php
if (! $someLogicToDetermineWhichVersionIsInstalled) {
    $this->markTestSkipped('Skipping as doctrine/migrations VERSION is not installed');
}
```

(We were running into Travis hour limits in November, which is why there were no build results flagging the problem for you; I made a change to a constructor and pushed it just now, in part to trigger a build, which is why we can now see build results.)

2021-01-07 08:20 UTC, cgrabenstein commented
Great! Will check it later, thanks for the heads up.

2021-01-16 11:08 UTC, edefimov commented on src/Check/DoctrineMigration.php
> +        if ($input instanceof Doctrine\Migrations\Configuration\Configuration
This is mistake: FQCN should be either prefixed with a backslash or added into use section of the file

2021-01-16 23:25 UTC, cgrabenstein commented
Ok, so I finally got the tests and everything running. Two issues remaining:
* Travis builds for php 5.6 error and I have no idea why or what to do.
* Coverage decreased. Reason seems to be that it's only measuring coverage with doctrine v1 or/and v2, which leaves the v3 code uncovered with tests, because those are skipped. Also, not really an idea what to do.

So, any help is really appreciated (ping @weierophinney)

2021-01-25 20:01 UTC, weierophinney commented
My suggestion is that we merge this post- #15, and release with 1.7.0; that way, we don't even have to worry about 5.6.

I'm putting it on my to-do; hopefully I can get to it this week.

2021-01-26 10:44 UTC, Ocramius commented
#15 released - re-targeting this for `1.8.0`, but will need a rebase

2021-01-26 11:27 UTC, cgrabenstein commented
@Ocramius Did the rebase. Pipeline's green also, finally! Sorry for the messy commits, if you prefer I can squash them together.

2021-01-26 11:38 UTC, Ocramius requested changes

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +     * @var array
What's the type of this `array`? What does it contain?

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +     * @var array
What's the type of this `array`? What does it contain?

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +        if ($input instanceof \Doctrine\Migrations\Configuration\Configuration
Can we add a comment explaining that this is for a different release?

2021-01-26 11:38 UTC, Ocramius commented on composer.json
> +        "doctrine/migrations": "^1.0 || ^2.0 || ^3.0",
Do we still need to support `^1`? At this point, it looks like it's really old (>2y, and `^2` is easy to migrate to), and we'll probably never get to test `^2` if our CI does a `--prefer-lowest` installation

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +            . 'If you are using doctrine/migrations ^1.0, '
We can drop this if we drop `^1`

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +            'Invalid Argument for DoctrineMigration check.' . PHP_EOL
You can simplify this through a `<<<'MESSAGE'` nowdoc block

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +    private function getAvailableVersionsFromDependencyFactory(DependencyFactory $dependencyFactory)
The return type for this should be documented and well-typed (it is an `array`: let's document the element types too)

2021-01-26 11:38 UTC, Ocramius commented on src/Check/DoctrineMigration.php
> +    private function getMigratedVersionsFromDependencyFactory(DependencyFactory $dependencyFactory)
The return type for this should be documented and well-typed (it is an `array`: let's document the element types too)

2021-01-26 11:49 UTC, Ocramius commented
@cgrabenstein ok, I did a review (didn't see this one before, sorry if it feels like I'm butting in).

Overall, I feel like dropping `^1` support is acceptable and will give us better test suite stability here.

2021-01-26 12:44 UTC, cgrabenstein commented
@Ocramius no worries, thanks for the review. I resolved your points and dropped support for `^1`

2021-01-26 12:49 UTC, Ocramius approved these changes
Excellent, thanks @cgrabenstein!

2021-01-26 12:50 UTC, merged