Allow PHP 8.2
laminas/laminas-diagnostics pull request #55
Opened 2022-11-04 08:02 UTC by IonBazan

Signed-off-by: Ion Bazan <ion.bazan@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | /no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Allowing PHP 8.2 in `composer.json` and build matrix.

2022-11-04 08:38 UTC, gsteel requested changes
It looks like CI on 8.2 is unlikely to pass. You can try ignoring platform reqs on 8.2 like this: https://github.com/laminas/laminas-filter/blob/2.24.x/.laminas-ci.json but as the required extensions are missing, it's likely a case of waiting for them to be available in apt.

2022-11-04 08:38 UTC, gsteel commented on composer.json
> +        "php": "^7.4 || ~8.0.0 || ~8.1.0 || ~8.2.0",
Can you also drop support for PHP 7.4, changing `config.platform.php` to `8.0.99`, and run a composer update to regenerate the lock file with latest deps. `composer bump --dev-only` would also help.

2022-11-09 16:56 UTC, Ocramius commented
This should be re-tried: the newer versions of CI include a bunch of 8.2 tooling now.

2022-11-11 12:25 UTC, Ocramius commented
Hmm, MongoDB missing is a bit of a pain, at this stage: will probably need to wait until after PHP 8.2 is released in Ondrej's PPAs.

2022-12-19 02:37 UTC, IonBazan commented
@Ocramius tests were failing because `DiskFree::$path` was set dynamically - solved by adding it there but Psalm is still complaining about some unrelated stuff. I suggest fixing that in a separate PR.

2022-12-19 02:38 UTC, samsonasik commented on src/Check/DiskFree.php
> +    private string $path;
need to be public unfortunatelly, mark with `@internal`

2022-12-19 03:45 UTC, samsonasik commented on src/Check/DiskFree.php
> +    public string $path;
new public property can't be typed, use `@var string` instead

2022-12-19 11:05 UTC, samsonasik commented
You can fix with run : 

```
composer cs-fix
```

Psalm need fixing as well https://github.com/laminas/laminas-diagnostics/actions/runs/3728718218/jobs/6323968842#step:4:506

2022-12-20 10:17 UTC, IonBazan commented
Thanks @samsonasik - forgot to run that before pushing. Regarding Psalm errors, I'll try to fix that in a separate PR to keep the changes scoped.

2022-12-20 10:19 UTC, Ocramius commented on composer.json
>          "vimeo/psalm": "^4.29.0"
Doing a full `composer update` probably led to the current CI failures around Psalm :thinking:

2022-12-20 10:28 UTC, IonBazan commented on composer.json
>          "vimeo/psalm": "^4.29.0"
Nope, only `laminas/laminas-loader` was bumped from 2.8.0 to 2.9.0 (to support PHP 8.2):

`composer diff upstream/1.23.x -l:`
| Dev Packages                                                        | Operation | Base  | Target | Link                                                                      |
|---------------------------------------------------------------------|-----------|-------|--------|---------------------------------------------------------------------------|
| [laminas/laminas-loader](https://github.com/laminas/laminas-loader) | Upgraded  | 2.8.0 | 2.9.0  | [Compare](https://github.com/laminas/laminas-loader/compare/2.8.0..2.9.0) |

2022-12-20 10:29 UTC, IonBazan commented on composer.json
>          "vimeo/psalm": "^4.29.0"
Oh I think that's because Psalm is now targeting PHP 8.0, while it's targeting 7.4 on `1.23.x`

2022-12-20 12:39 UTC, Ocramius commented
The remaining psalm issues are something I fixed in #62, but no time to pursue that further right now.

I suggest re-generating the baseline: please make sure you do so from a compatible environment (`docker run --rm -ti -v $(pwd):/app -w /app php:8.0 bash` may help)

2022-12-20 15:43 UTC, IonBazan commented
Thanks for the tips, @Ocramius - turned out I had to pass `--set-baseline=psalm-baseline.xml` too to add new entries. CI is green now ✅

2022-12-20 15:45 UTC, Ocramius approved these changes
LGTM, thanks @IonBazan

2022-12-20 15:45 UTC, merged