Add possibility to set zero port for memcache and memcached checkers
laminas/laminas-diagnostics pull request #64
Opened 2022-12-06 15:16 UTC by amicus-alex

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
It is impossible to pass zero to a port argument for Memcache and Memcached checkers when using UNIX domain sockets. But the documentation ([memcache.addServer](https://www.php.net/manual/en/memcache.addserver.php), [memcached.addServer](https://www.php.net/manual/en/memcached.addserver.php)) says "As of version 2.0.0b1, set this parameter to 0 when using UNIX domain sockets."

2022-12-07 01:29 UTC, Ocramius requested changes
Idea seems sensible to me, but I'd also need:

 * A test that shows port `0` being used
 * Documentation about how to connect via socket

2022-12-14 15:00 UTC, Ocramius approved these changes
LGTM: would still endorse minor docblock adjustments for clarity :)

2022-12-14 15:00 UTC, Ocramius commented on src/Check/Memcache.php
> +     *                     Set this parameter to 0 when using UNIX domain sockets.
Perhaps `positive-int|0`?

2022-12-14 15:00 UTC, Ocramius commented on src/Check/Memcached.php
> +     *                     Set this parameter to 0 when using UNIX domain sockets.
Perhaps `positive-int|0`?

2022-12-14 15:01 UTC, Ocramius commented
A rebase on top of `1.22.x` is endorsed: we changed a lot in the type analysis, so please don't try to run `vimeo/psalm` on this change until rebased

2022-12-15 17:02 UTC, Ocramius approved these changes
LGTM, thanks @amicus-alex!

2022-12-15 17:03 UTC, merged

2022-12-15 20:15 UTC, ok-up commented
Thank you, @Ocramius 😉